language: python
python:
  - "3.7"
env:
  - NODE_VERSION="12.14.1"
before_install:
  - nvm install $NODE_VERSION
install:
  - make venv
script:
  - make test

deploy:
  - provider: script
    script: make coverage
    on:
      branch: master
